compressionLevel: 9

defaultLanguageName: node

defaultSemverRangePrefix: ^

enableColors: true

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmScopes:
  '@developer-kit':
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN}
    npmPublishRegistry: https://registry.npmjs.org/
    npmRegistryServer: https://registry.npmjs.org/

pnpEnableEsmLoader: true

progressBarStyle: hogsfather

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
